spring:
  profiles:
    active: dev
  application:
    name: xcms-app
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
server:
  port: 8080

xcms:
  security:
    permit-all-matchers:
      - /auth/**
      - /error
    ignore-matchers:
      - /actuator/**
      - /actuator
      - /h2-console/**
